### ISSUE TITLE
Where are the API urls for app.properties ?

### ISSUE THREAD

**Issue by johnoscott** [nextux/iview-android-tv#12]
Where do i source the URLs for the API mentioned below ? 

To build

Create a file named app.properties in the project that defines the API urls for the ABC iview services. See gradle build error messages for details.

**Comment by nextux** [comment]
Hi @johnoscott 

I am not able to provide the URLs for legal reasons, I am afraid.  As crappy as the answer usually is "a google search" will be your friend here, or a search on Whirlpool, as I believe the URLs were listed there some time ago.

**Comment by johnoscott** [comment]
OK I did look on Whirlpool ; I will look again.
Also, what is the format of this file (can you provide an example ?)

**Comment by nextux** [comment]
SBS_API_URL="http://url"
SBS_VIDEO_URL="http://url"
IVIEW_AUTH_URL="https://url"
IVIEW_API_URL="http://url"
