### ISSUE TITLE
Most boxes are blank

### ISSUE THREAD

**Issue by jamieskella** [nextux/iview-android-tv#6]
Only a handful of images show up, the rest remain blank boxes (new Shield).

**Comment by nextux** [comment]
Is there any option to post a screenshot of this?

If you connect a keyboard to your Shield, pressing the "Print Screen" key should dump a screenshot into ExternalStorage/Pictures/Screenshots

**Comment by vipoo** [comment]
Recently installed the app on new Nividia Shield

The old app also had the same issue.

![screenshot_20170225-093216](https://cloud.githubusercontent.com/assets/427518/23323687/cf573802-fb3d-11e6-8f50-ab1a4fd6e1c6.png)

**Comment by 3432** [comment]
Looks to be an issue with the Picasso library on the Nvidia Shield. Updating the dependencies to a newer 2.6 snapshot of Picasso from Sonatype's repository and rebuilding fixes the thumbnails.

**Comment by nextux** [comment]
Happy to fix it on this end (been a little busy of late, apologies) but if you have it fixed on a forked copy of the repo, I'm happy to accept a pull request.

**Comment by nextux** [comment]
Will rebuild new binaries shortly
