### ISSUE TITLE
Videos do not play

### ISSUE THREAD

**Issue by iamjmulligan** [nextux/iview-android-tv#8]
Using version 1.2.3 on a NVIDIA Shield TV when I try and play any video the player screen opens but just sits there blankly loading forever.

**Comment by nextux** [comment]
Were the videos playing in the previous version?

**Comment by iamjmulligan** [comment]
I don't think they were. Just that with the update to fix the thumbnails
(which I don't think fixed the issue) I felt the need to submit the report.
I'll reinstall an older version to check.

**Comment by iamjmulligan** [comment]
Well trying to install 1.1.0, then 1.2.2 and then 1.2.3 had the issue go away, so I'll close it. Dunno what happened.

**Comment by nextux** [comment]
Unfortunately I don't own a shield device. I'll give it a go on my Sony and
my Nexus Player when I get home in case it is server side.
