### ISSUE TITLE
Using search crashes iView app

### ISSUE THREAD

**Issue by iamjmulligan** [nextux/iview-android-tv#9]
Using the NVIDIA Shield TV (at least) I've noticed that clicking on the search icon within the app crashes the app. I first noticed this with 1.2.3, but going back to 1.2.2 and 1.1.1 all have the same issue. As thats the only AndroidTV device I have i have no idea whether its common across AndroidTV devices or something ShieldTV or specific to my OS level (AndroidTV 7.0 - 1/12/16 Patch Level).

**Comment by nextux** [comment]
Thank you for your active participation in finding issues @iamjmulligan . I really appreciate it. However this one is a duplicate of https://github.com/nextux/iview-android-tv/issues/1 .  It has been on the to-do list for a bit, but I am slowly digesting the code for a rewrite using exoplayer 2. When this occurs, I'll introduce a check for permissions. Basically you'll need to set the permissions as per https://github.com/nextux/iview-android-tv/issues/1
